parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     lob
    database_user:     root
    database_password: ~

    mailer_transport:  mail
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            fr
    secret:            TokenSecretLeagueOfBraveryPantoufle
    max_users_on_page: 50
    max_team_on_page: 50
