parameters:
#    websio_utilisateur.example.class: Websio\UtilisateurBundle\Example

services:
#    websio_utilisateur.example:
#        class: %websio_utilisateur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
